### ISSUE TITLE
Can't get code to run

### ISSUE THREAD

**Issue by isaacgerg** [dvbuntu/autonomous#1]
Hi Dan,

I am trying to run your code from the repo but running into some trouble.  I have been able to generate the npz files using shrink.py. When i run complex.py, it complains about array sizes.

Can you give some guidance on how to boostrap this process?

Thanks,
isaac

**Comment by isaacgerg** [comment]
In complex.py, i get the following after loading the npz files.

imgs.shape
(7600, 3, 64, 64)
speedx.shape
(7600, 2)
targets.shape
(7600, 2)

Is this correct?

**Comment by dvbuntu** [comment]
There was a problem in `shrink.py` that I only recently fixed.  Have you tried the pre-shrunk data at https://drive.google.com/open?id=0B0zbVEese408WjYtWGdJWTF0Rjg?  The "big" ones should have 17241 training samples with 1916 validation samples.

In general, I'm using the scripts as scratchpads where I build the model, so I don't always run every line.  I'm working on `simple_steer.py` at the moment right now.  It's more or less runnable up until line 136 or so, just after the training.

**Comment by isaacgerg** [comment]
Where is simple_steer.py?

**Comment by dvbuntu** [comment]
Derp, I forgot to push it.  I found this out the hard way when I went to pull code to the embedded computer.  I'll have that up tonight.

**Comment by isaacgerg** [comment]
Dan, I was able to half the amount of error on your model with a few changes.  I would like to send you the code so you can verify.  I cant find your email, can you send me one at isaac dot gerg at gergltd.com?  Will email you the code.

**Comment by dvbuntu** [comment]
I've sent you my email.  A pull request would also be fine.  Thanks for taking a crack at this!
